"""crear tabla asignaciones

Revision ID: 0b581e42dfdc
Revises: 171cb48fb910
Create Date: 2026-07-05 10:24:40.276045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b581e42dfdc'
down_revision: Union[str, Sequence[str], None] = '171cb48fb910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asignaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escuela_id', sa.Integer(), nullable=False),
    sa.Column('grado_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('bloque_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bloque_id'], ['bloques_horarios.id'], ),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ),
    sa.ForeignKeyConstraint(['escuela_id'], ['escuelas.id'], ),
    sa.ForeignKeyConstraint(['grado_id'], ['grados.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asignaciones_id'), 'asignaciones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asignaciones_id'), table_name='asignaciones')
    op.drop_table('asignaciones')
    # ### end Alembic commands ###
