"""crear tablas docentes y disponibilidad

Revision ID: 171cb48fb910
Revises: 539858c2febf
Create Date: 2026-07-04 22:49:07.186209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '171cb48fb910'
down_revision: Union[str, Sequence[str], None] = '539858c2febf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escuela_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('cargo_modulos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['escuela_id'], ['escuelas.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docentes_id'), 'docentes', ['id'], unique=False)
    op.create_table('disponibilidad_docente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('bloque_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bloque_id'], ['bloques_horarios.id'], ),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disponibilidad_docente_id'), 'disponibilidad_docente', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disponibilidad_docente_id'), table_name='disponibilidad_docente')
    op.drop_table('disponibilidad_docente')
    op.drop_index(op.f('ix_docentes_id'), table_name='docentes')
    op.drop_table('docentes')
    # ### end Alembic commands ###
