"""crear tabla grados

Revision ID: 404456762337
Revises: 6380bc0c9e21
Create Date: 2026-07-01 21:51:55.961946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '404456762337'
down_revision: Union[str, Sequence[str], None] = '6380bc0c9e21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escuela_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('maestra', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['escuela_id'], ['escuelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grados_id'), 'grados', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grados_id'), table_name='grados')
    op.drop_table('grados')
    # ### end Alembic commands ###
