"""crear tabla bloques horarios

Revision ID: 6380bc0c9e21
Revises: c240809b7c30
Create Date: 2026-07-01 21:22:32.600865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6380bc0c9e21'
down_revision: Union[str, Sequence[str], None] = 'c240809b7c30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bloques_horarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('escuela_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('tipo_bloque', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['escuela_id'], ['escuelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bloques_horarios_id'), 'bloques_horarios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bloques_horarios_id'), table_name='bloques_horarios')
    op.drop_table('bloques_horarios')
    # ### end Alembic commands ###
