"""agregar dia_cobertura a grados

Revision ID: f509490efc63
Revises: 0b581e42dfdc
Create Date: 2026-08-12 01:25:45.613221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f509490efc63'
down_revision: Union[str, Sequence[str], None] = '0b581e42dfdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grados', sa.Column('dia_cobertura', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grados', 'dia_cobertura')
    # ### end Alembic commands ###
